name := "apibuilder-commons-scala2"

organization := "io.apibuilder"

ThisBuild / scalaVersion := "2.13.15"

lazy val allScalacOptions = Seq(
  "-deprecation",
  "-feature",
  "-Xfatal-warnings",
  "-unchecked",
  "-Xcheckinit",
  "-Xlint:adapted-args",
  "-Wconf:src=generated/.*:silent",
  "-Wconf:src=target/.*:silent", // silence the unused imports errors generated by the Play Routes
)

lazy val resolversSettings = Seq(
  resolvers += "jitpack" at "https://jitpack.io"
)

lazy val root = project
  .in(file("."))
  .settings(
    testOptions += Tests.Argument("-oDF"),
    libraryDependencies ++= Seq(
      "org.typelevel" %% "cats-core" % "2.12.0",
      "org.scalatest" %% "scalatest" % "3.2.19" % Test,
    ),
    scalacOptions ++= allScalacOptions,
  )
